global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pure_health_backend_mlops'
    metrics_path: '/api/admin/mlops-pipeline/'
    static_configs:
      - targets: ['127.0.0.1:8000', 'project-working-snojkumar968-9939s-projects.vercel.app']

  - job_name: 'pure_health_system_metrics'
    metrics_path: '/api/admin/system-metrics/'
    static_configs:
      - targets: ['127.0.0.1:8000']
