# Generated by Django 6.0.7 on 2026-07-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditlogmodel',
            name='compliance_category',
            field=models.CharField(default='NABH_HIPAA_AUDIT', max_length=100),
        ),
        migrations.AddField(
            model_name='adminauditlogmodel',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning / Overrides'), ('CRITICAL', 'Critical Emergency Action')], db_index=True, default='INFO', max_length=20),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='consultation_type',
            field=models.CharField(choices=[('OPD', 'Outpatient Department (OPD)'), ('IPD', 'Inpatient Department (IPD)'), ('Emergency', 'Emergency Care Triage'), ('Teleconsultation', 'AIIMS Tele-Medicine')], default='OPD', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology (CTVS)'), ('Neurology', 'Neurology & Neurosurgery'), ('Orthopedics', 'Orthopedics & Trauma'), ('Pediatrics', 'Pediatrics & Neonatology'), ('General_Medicine', 'General Medicine'), ('Emergency_Care', 'Emergency & Trauma Care'), ('Oncology', 'Medical & Surgical Oncology')], db_index=True, default='General_Medicine', max_length=100),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine OPD'), ('urgent', 'Urgent Referral'), ('emergency', 'Critical / Emergency Triage')], db_index=True, default='routine', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='token_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=50),
        ),
    ]
