# Generated by Django 6.0.7 on 2026-07-27 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_adminauditlogmodel_compliance_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRosterModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('doctor_name', models.CharField(max_length=255, unique=True)),
                ('department', models.CharField(choices=[('General_Consultation', 'General Consultation & Preventive Care'), ('Diagnostic_Support', 'Diagnostic & Laboratory Support'), ('Chronic_Care', 'Chronic Disease Management (Diabetes/Hypertension)'), ('Wellness_Guidance', 'Wellness & Lifestyle Guidance'), ('Cardiology', 'Cardiology & Cardiovascular Care'), ('Neurology', 'Neurology & Nerve Health'), ('Orthopedics', 'Orthopedics & Joint Care'), ('Emergency_Care', 'Emergency & Urgent Triage')], default='General_Consultation', max_length=100)),
                ('shift_hours', models.CharField(default='09:00 AM - 05:00 PM', max_length=100)),
                ('duty_status', models.CharField(choices=[('on_duty', 'On Duty (OPD Active)'), ('in_surgery', 'In Surgery / Procedure'), ('on_break', 'On Break'), ('off_duty', 'Off Duty')], default='on_duty', max_length=50)),
                ('room_number', models.CharField(default='OPD Room 101', max_length=50)),
            ],
            options={
                'db_table': 'doctor_roster',
            },
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='video_room_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='consultation_type',
            field=models.CharField(choices=[('OPD', 'Outpatient Department (OPD)'), ('IPD', 'Inpatient Department (IPD)'), ('Emergency', 'Emergency Triage'), ('Teleconsultation', 'Tele-Health Consultation')], default='OPD', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='department',
            field=models.CharField(choices=[('General_Consultation', 'General Consultation & Preventive Care'), ('Diagnostic_Support', 'Diagnostic & Laboratory Support'), ('Chronic_Care', 'Chronic Disease Management (Diabetes/Hypertension)'), ('Wellness_Guidance', 'Wellness & Lifestyle Guidance'), ('Cardiology', 'Cardiology & Cardiovascular Care'), ('Neurology', 'Neurology & Nerve Health'), ('Orthopedics', 'Orthopedics & Joint Care'), ('Emergency_Care', 'Emergency & Urgent Triage')], db_index=True, default='General_Consultation', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine OPD Consultation'), ('urgent', 'Urgent Referral'), ('emergency', 'Emergency Triage')], db_index=True, default='routine', max_length=50),
        ),
    ]
