# Generated by Django 6.0.7 on 2026-07-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_doctorrostermodel_appointmentmodel_video_room_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='consultation_fee_inr',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='emergency_escalation_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctorrostermodel',
            name='consultation_fee_inr',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorrostermodel',
            name='current_queue_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorrostermodel',
            name='max_daily_patients',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='appointment_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='doctorrostermodel',
            name='duty_status',
            field=models.CharField(choices=[('on_duty', 'On Duty (OPD Active)'), ('in_surgery', 'In Surgery / Procedure'), ('on_break', 'On Break'), ('off_duty', 'Off Duty')], db_index=True, default='on_duty', max_length=50),
        ),
        migrations.AddIndex(
            model_name='adminauditlogmodel',
            index=models.Index(fields=['severity', 'created_at'], name='admin_audit_severit_1438c8_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlogmodel',
            index=models.Index(fields=['admin_email', 'severity'], name='admin_audit_admin_e_f7cb71_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentmodel',
            index=models.Index(fields=['department', 'status', 'is_deleted'], name='appointment_departm_c9ba20_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentmodel',
            index=models.Index(fields=['appointment_date', 'status'], name='appointment_appoint_b9472b_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentmodel',
            index=models.Index(fields=['priority', 'status'], name='appointment_priorit_dfab1b_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorrostermodel',
            index=models.Index(fields=['duty_status', 'department'], name='doctor_rost_duty_st_dde57d_idx'),
        ),
    ]
