# Generated by Django 6.0.7 on 2026-07-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_appointmentmodel_consultation_fee_inr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorrostermodel',
            name='estimated_wait_time_minutes',
            field=models.IntegerField(default=15),
        ),
    ]
