# Generated by Django 6.0.7 on 2026-09-01 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(default='Dr. Divit Shah', max_length=255)),
                ('category', models.CharField(default='Preventive Health', max_length=100)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'blog_posts',
            },
        ),
        migrations.CreateModel(
            name='ContactInquiryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'contact_inquiries',
            },
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('qualifications', models.CharField(default='MBBS, MD', max_length=255)),
                ('experience_years', models.IntegerField(default=10)),
                ('bio', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('consultation_fee_inr', models.DecimalField(decimal_places=2, default=600.0, max_digits=10)),
                ('opd_timings', models.CharField(default='09:00 AM - 05:00 PM', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='GalleryImageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Facility', max_length=100)),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gallery_images',
            },
        ),
        migrations.CreateModel(
            name='MedicalServiceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(default='General', max_length=100)),
                ('description', models.TextField()),
                ('full_details', models.TextField(blank=True, null=True)),
                ('icon_name', models.CharField(default='Stethoscope', max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('consultation_fee_inr', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'medical_services',
            },
        ),
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('treatment', models.CharField(default='General OPD Care', max_length=255)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'testimonials',
            },
        ),
    ]
