from django.urls import path
from apps.administration.views import (
    SystemHealthView,
    AdminDashboardView,
    AuditLogListView,
    AppointmentListCreateView,
    AppointmentDetailView,
    AppointmentPDFSlipView,
    SeedDemoDataView,
    TokenTrackerView,
    RazorpayOrderCreateView,
    WhatsAppNotificationSendView,
    PrescriptionSummarizerAiView,
    GeminiAiChatbotView,
    SystemMetricsView,
    HospitalStatsView,
    PatientFeedbackView,
    IcuOccupancyTelemetryView,
    PharmacyBloodBankTelemetryView,
    UnifiedAiModelSuiteView,
    MlOpsPipelineView,
    DeepTrainModelsView,
    AmbulanceDispatchView,
    KaggleGitHubDatasetView,
    TrainKaggleModelsView,
    NextGen50FeaturesView,
    GenomicSequencingView,
    RadiologyXrayAiView,
    FineTuneAiModelsView,
    EmailNotificationSendView,
    LiveQueueSseView,
    BulkInsertClinicalDataView,
    SystemDiagnosticsView,
    DeepAiSuperEngineView,
    SecurityAuditView,
    IotMedicalDeviceTelemetryView,
    DatabaseAiIngestionView,
    VoiceDictationView,
    CdssAgentView,
    FhirPatientView,
    CloudflareSecurityServerView,
    PharmacyOrderTrackingView,
    OrganTransplantMatchingView,
    TrafficManagementServerView,
    MegaDatasetAiMlopsPipelineView,
    RfidIndoorTrackingView,
    UvcRobotSchedulingView,
    RetinalScanAiView,
    HealthKitGatewayView,
    VoiceCallDispatchView,
    DoctorQueueWaitTimeView,
    DigitalPrescriptionGeneratorView,
    DrugAllergyCrossReactionView,
    StripePaymentSessionView,
    UpiInstantDynamicQrView,
    PayPalOrderCreateView,
    TaxInvoiceEmailDispatchView,
    AutomatedMlopsRetrainView,
    DatabaseShardingHealthView,
    MultiModalAiSuperBrainView,
    PharmacogenomicsAiView,
)

urlpatterns = [
    # System Health & Integration APIs (Udbhav - Module 4)
    path('health/', SystemHealthView.as_view(), name='system-health'),
    path('seed-demo-data/', SeedDemoDataView.as_view(), name='seed-demo-data'),
    path('system-metrics/', SystemMetricsView.as_view(), name='system-metrics'),
    path('hospital-stats/', HospitalStatsView.as_view(), name='hospital-stats'),
    path('patient-feedback/', PatientFeedbackView.as_view(), name='patient-feedback'),
    path('icu-occupancy/', IcuOccupancyTelemetryView.as_view(), name='icu-occupancy'),
    path('pharmacy-blood-bank/', PharmacyBloodBankTelemetryView.as_view(), name='pharmacy-blood-bank'),
    path('ai-model-suite/', UnifiedAiModelSuiteView.as_view(), name='ai-model-suite'),
    path('mlops-pipeline/', MlOpsPipelineView.as_view(), name='mlops-pipeline'),
    path('deep-train-models/', DeepTrainModelsView.as_view(), name='deep-train-models'),
    path('ambulance-dispatch/', AmbulanceDispatchView.as_view(), name='ambulance-dispatch'),
    path('kaggle-github-datasets/', KaggleGitHubDatasetView.as_view(), name='kaggle-github-datasets'),
    path('train-kaggle-models/', TrainKaggleModelsView.as_view(), name='train-kaggle-models'),
    path('next-gen-50-features/', NextGen50FeaturesView.as_view(), name='next-gen-50-features'),
    path('genomic-sequencing/', GenomicSequencingView.as_view(), name='genomic-sequencing'),
    path('radiology-xray-ai/', RadiologyXrayAiView.as_view(), name='radiology-xray-ai'),
    path('fine-tune-ai-models/', FineTuneAiModelsView.as_view(), name='fine-tune-ai-models'),
    path('send-email-notification/', EmailNotificationSendView.as_view(), name='send-email-notification'),
    path('live-queue-sse/', LiveQueueSseView.as_view(), name='live-queue-sse'),
    path('bulk-insert-clinical-data/', BulkInsertClinicalDataView.as_view(), name='bulk-insert-clinical-data'),
    path('system-diagnostics/', SystemDiagnosticsView.as_view(), name='system-diagnostics'),
    path('deep-ai-super-engine/', DeepAiSuperEngineView.as_view(), name='deep-ai-super-engine'),
    path('security-audit/', SecurityAuditView.as_view(), name='security-audit'),
    path('iot-medical-devices/', IotMedicalDeviceTelemetryView.as_view(), name='iot-medical-devices'),
    path('database-ai-ingestion/', DatabaseAiIngestionView.as_view(), name='database-ai-ingestion'),
    path('voice-dictation/', VoiceDictationView.as_view(), name='voice-dictation'),
    path('cdss-agent/', CdssAgentView.as_view(), name='cdss-agent'),
    path('fhir/Patient/', FhirPatientView.as_view(), name='fhir-patient'),
    path('cloudflare-security-server/', CloudflareSecurityServerView.as_view(), name='cloudflare-security-server'),
    path('pharmacy-order-tracking/', PharmacyOrderTrackingView.as_view(), name='pharmacy-order-tracking'),
    path('organ-transplant-matching/', OrganTransplantMatchingView.as_view(), name='organ-transplant-matching'),
    path('traffic-management-server/', TrafficManagementServerView.as_view(), name='traffic-management-server'),
    path('mega-dataset-mlops/', MegaDatasetAiMlopsPipelineView.as_view(), name='mega-dataset-mlops'),
    path('rfid-indoor-tracking/', RfidIndoorTrackingView.as_view(), name='rfid-indoor-tracking'),
    path('uvc-robot-scheduling/', UvcRobotSchedulingView.as_view(), name='uvc-robot-scheduling'),
    path('retinal-scan-ai/', RetinalScanAiView.as_view(), name='retinal-scan-ai'),
    path('healthkit-gateway/', HealthKitGatewayView.as_view(), name='healthkit-gateway'),
    path('trigger-voice-call/', VoiceCallDispatchView.as_view(), name='trigger-voice-call'),
    path('queue-wait-time/', DoctorQueueWaitTimeView.as_view(), name='queue-wait-time'),
    path('generate-digital-rx/', DigitalPrescriptionGeneratorView.as_view(), name='generate-digital-rx'),
    path('drug-allergy-shield/', DrugAllergyCrossReactionView.as_view(), name='drug-allergy-shield'),
    path('create-stripe-session/', StripePaymentSessionView.as_view(), name='create-stripe-session'),
    path('create-upi-qr/', UpiInstantDynamicQrView.as_view(), name='create-upi-qr'),
    path('create-paypal-order/', PayPalOrderCreateView.as_view(), name='create-paypal-order'),
    path('send-tax-invoice-email/', TaxInvoiceEmailDispatchView.as_view(), name='send-tax-invoice-email'),
    path('automated-mlops-retrain/', AutomatedMlopsRetrainView.as_view(), name='automated-mlops-retrain'),
    path('database-sharding-health/', DatabaseShardingHealthView.as_view(), name='database-sharding-health'),
    path('multi-modal-ai-super-brain/', MultiModalAiSuperBrainView.as_view(), name='multi-modal-ai-super-brain'),
    path('pharmacogenomics-ai/', PharmacogenomicsAiView.as_view(), name='pharmacogenomics-ai'),





    # Admin Analytics & Compliance Auditing APIs
    path('dashboard/', AdminDashboardView.as_view(), name='admin-dashboard'),
    path('audit-logs/', AuditLogListView.as_view(), name='audit-log-list'),

    # Appointment Management & OPD Token APIs
    path('appointments/', AppointmentListCreateView.as_view(), name='appointment-list-create'),
    path('appointments/track/<str:token_number>/', TokenTrackerView.as_view(), name='appointment-track'),
    path('appointments/<uuid:pk>/', AppointmentDetailView.as_view(), name='appointment-detail'),
    path('appointments/<uuid:pk>/slip/', AppointmentPDFSlipView.as_view(), name='appointment-pdf-slip'),

    # Next-Gen Innovations (Razorpay, Twilio WhatsApp, Gemini AI Summarizer, Gemini Chatbot)
    path('create-razorpay-order/', RazorpayOrderCreateView.as_view(), name='create-razorpay-order'),
    path('send-whatsapp-notification/', WhatsAppNotificationSendView.as_view(), name='send-whatsapp-notification'),
    path('summarize-prescription/', PrescriptionSummarizerAiView.as_view(), name='summarize-prescription'),
    path('chat-gemini-ai/', GeminiAiChatbotView.as_view(), name='chat-gemini-ai'),
]
